version: '3'
services:
  athina-web:
    image: athinaedu/athina-web:latest
    command: bash -c "python manage.py collectstatic --noinput && gunicorn --bind :8001 athinaweb.wsgi:application"
    volumes:
      - ./athina_files/:/code/athina_files/
      - ./db.sqlite3:/code/db.sqlite3
      - ./athinaweb/settings_secret.py:/code/athinaweb/settings_secret.py
      - ./static_files:/code/static_files
    expose:
      - "8001"
    depends_on:
      - "db"
    environment:
      ATHINA_MYSQL_HOST: "db"
      ATHINA_MYSQL_PORT: "3306"
      ATHINA_MYSQL_USERNAME: "athina"
      ATHINA_MYSQL_PASSWORD: "pae1eesahD"
    networks:
      athina_net:
        ipv4_address: 172.29.1.2
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - ./certs/:/etc/certs/
      - ./static_files:/code/static_files
    networks:
      athina_net:
        ipv4_address: 172.29.1.1
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    depends_on:
      - "athina-web"
  athina:
    image: athinaedu/athina:latest
    environment:
      ATHINA_MYSQL_HOST: "db"
      ATHINA_MYSQL_PORT: "3306"
      ATHINA_MYSQL_USERNAME: "athina"
      ATHINA_MYSQL_PASSWORD: "pae1eesahD"
      ATHINA_WEB_URL: "https://127.0.0.1"
      GLOBAL_MEMORY_LIMIT: 80
      DOCKER_MEMORY_LIMIT: "2g"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./athina_files/:/code/athina_files/
      - ./logs/:/code/logs/
      - /tmp:/tmp
    depends_on:
      - "nginx"
      - "athina-web"
      - "db"
    command: ["--json", "http://172.29.1.1/assignments/api/", "-s", "-v"]
    networks:
      athina_net:
        ipv4_address: 172.29.1.3
  db:
    image: mysql:5.7
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: "athina_web"
      MYSQL_USER: "athina"
      MYSQL_PASSWORD: "pae1eesahD"
      MYSQL_ROOT_PASSWORD: "pae1eesahD"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      athina_net:
        ipv4_address: 172.29.1.4

networks:
    athina_net:
        ipam:
            driver: default
            config:
                - subnet: 172.29.0.0/16
